// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Contributors sidebar - individual contributors
  contributorsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'contributors',
    },
  ],

  // Projects sidebar - project teams and maintainers
  projectsSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'projects',
    },
  ],

  // Community sidebar - staff, TAG leads, community coordination
  communitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'community', 
    },
  ],

  // Resources sidebar - tools, services, templates
  resourcesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'resources',
    },
  ],

  // Legacy sidebar for backward compatibility
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
